version: '3.8'
services:
  tests:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - dist:/app/dist
      - reports:/app/reports
    environment:
      - NODE_ENV=development
    command: bash
    stdin_open: true
    tty: true
    user: developer

volumes:
  node_modules:
  dist:
  reports: