version: '3.8'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
    tty: true
    stdin_open: true